[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
line-length = 88

[tool.ruff.lint]
# E/W - стандарты PEP8
# F - Pyflakes (ошибки логики)
# I - сортировка импортов
# UP - обновление синтаксиса (pyupgrade)
# B - Bugbear (поиск багов)
select = ["E", "W", "F", "I", "UP", "B"]

ignore = ["B008", "E501"]

[tool.ruff.lint.isort]
known-first-party = ["auth", "core", "database", "main", "models"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true